In [ ]:
import pandas as pd
import asyncio
import os
import requests
from datasets import load_dataset
from tqdm.notebook import tqdm

In [8]:
splits = {'train': 'data/train-00000-of-00001-0084e041f1902997.parquet', 'validation': 'data/validation-00000-of-00001-e3c37e369512a3aa.parquet'}
df = pd.read_parquet("hf://datasets/phiyodr/coco2017/" + splits["validation"])
df

,license,file_name,coco_url,height,width,date_captured,flickr_url,image_id,ids,captions
0,4,val2017/000000397133.jpg,http://images.cocodataset.org/val2017/00000039...,427,640,2013-11-14 17:02:52,http://farm7.staticflickr.com/6116/6255196340_...,397133,"[370509, 370584, 372252, 372765, 375891]","[A man is in a kitchen making pizzas., Man in ..."
1,1,val2017/000000037777.jpg,http://images.cocodataset.org/val2017/00000003...,230,352,2013-11-14 20:55:31,http://farm9.staticflickr.com/8429/7839199426_...,37777,"[597185, 598568, 599939, 601877, 603617]",[The dining table near the kitchen has a bowl ...
2,4,val2017/000000252219.jpg,http://images.cocodataset.org/val2017/00000025...,428,640,2013-11-14 22:32:02,http://farm4.staticflickr.com/3446/3232237447_...,252219,"[107395, 109132, 111433, 114199, 114511]",[a person with a shopping cart on a city stree...
3,1,val2017/000000087038.jpg,http://images.cocodataset.org/val2017/00000008...,480,640,2013-11-14 23:11:37,http://farm8.staticflickr.com/7355/8825114508_...,87038,"[647151, 653244, 653436, 654318, 654543]",[A person on a skateboard and bike at a skate ...
4,6,val2017/000000174482.jpg,http://images.cocodataset.org/val2017/00000017...,388,640,2013-11-14 23:16:55,http://farm8.staticflickr.com/7020/6478877255_...,174482,"[429740, 430565, 430589, 431771, 435809]","[a blue bike parked on a side walk , A bicycle..."
...,...,...,...,...,...,...,...,...,...,...
4995,3,val2017/000000512403.jpg,http://images.cocodataset.org/val2017/00000051...,640,529,2013-11-24 05:12:53,http://farm1.staticflickr.com/143/350452845_fa...,512403,"[324034, 324310, 325873, 331555, 340180]","[A vase of feathers on a shelf by some art., T..."
4996,4,val2017/000000168974.jpg,http://images.cocodataset.org/val2017/00000016...,500,375,2013-11-24 07:19:48,http://farm3.staticflickr.com/2360/2063838083_...,168974,"[189446, 193049, 194774, 197339, 200009]",[A little baby sitting on the floor with a cel...
4997,1,val2017/000000552775.jpg,http://images.cocodataset.org/val2017/00000055...,500,375,2013-11-24 10:38:31,http://farm4.staticflickr.com/3136/3106037881_...,552775,"[237047, 239012, 239555, 248879, 251210]",[A man pokes his head in front of an oven open...
4998,3,val2017/000000394940.jpg,http://images.cocodataset.org/val2017/00000039...,640,426,2013-11-24 13:47:05,http://farm9.staticflickr.com/8227/8566023505_...,394940,"[700326, 705021, 709812, 710715, 711423]","[a kid eating a cake on table looking around,..."
4999,2,val2017/000000015335.jpg,http://images.cocodataset.org/val2017/00000001...,480,640,2013-11-25 14:00:10,http://farm6.staticflickr.com/5533/10257288534...,15335,"[505078, 505954, 505978, 507940, 509731]",[A group of people sitting at a table with foo...

Download the data at the given links to the data directory

In [ ]:

def background(f):
	def wrapped(*args, **kwargs):
		return asyncio.get_event_loop().run_in_executor(None, f, *args, **kwargs)
	return wrapped

@background
def download_image(url, name):
	response = requests.get(url)
	if response.status_code == 200:
		with open(name, 'wb') as f:
			f.write(response.content)

if not os.path.exists("./data/val2017"): os.mkdir("./data/val2017")
tasks = []
for i, row in df.iterrows():
	tasks.append(download_image(row["coco_url"], "./data/" + row["file_name"]))
await asyncio.gather(*tasks)

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ...]

In [9]:
neg_df = pd.DataFrame({"data": df["file_name"].tolist(), "positive": [False]*len(df)})
neg_df

                          data  positive
0     val2017/000000397133.jpg     False
1     val2017/000000037777.jpg     False
2     val2017/000000252219.jpg     False
3     val2017/000000087038.jpg     False
4     val2017/000000174482.jpg     False
...                        ...       ...
4995  val2017/000000512403.jpg     False
4996  val2017/000000168974.jpg     False
4997  val2017/000000552775.jpg     False
4998  val2017/000000394940.jpg     False
4999  val2017/000000015335.jpg     False

[5000 rows x 2 columns]

Now I want to grab the positive face examples

In [ ]:

ds = load_dataset("tpremoli/CelebA-attrs", split="test", streaming=True)

In [11]:

i = 0
names = []
if not os.path.exists("./data/celeba"): os.mkdir("./data/celeba")
for d in tqdm(ds.take(5_000), total=5_000):
	n = f"celeba/{i}.jpg"
	d["image"].save("./data/" + n)
	names.append(n)
	i+=1

  0%|          | 0/5000 [00:00<?, ?it/s]

In [12]:
pos_df = pd.DataFrame({"data": names, "positive": [True]*5_000})
pos_df

                 data  positive
0        celeba/0.jpg      True
1        celeba/1.jpg      True
2        celeba/2.jpg      True
3        celeba/3.jpg      True
4        celeba/4.jpg      True
...               ...       ...
4995  celeba/4995.jpg      True
4996  celeba/4996.jpg      True
4997  celeba/4997.jpg      True
4998  celeba/4998.jpg      True
4999  celeba/4999.jpg      True

[5000 rows x 2 columns]

In [14]:
df = pd.concat((pos_df, neg_df))
df

                          data  positive
0                 celeba/0.jpg      True
1                 celeba/1.jpg      True
2                 celeba/2.jpg      True
3                 celeba/3.jpg      True
4                 celeba/4.jpg      True
...                        ...       ...
4995  val2017/000000512403.jpg     False
4996  val2017/000000168974.jpg     False
4997  val2017/000000552775.jpg     False
4998  val2017/000000394940.jpg     False
4999  val2017/000000015335.jpg     False

[10000 rows x 2 columns]

In [17]:
df.to_parquet("./data/tasks/face_task.parquet", index=False)